const express = require("express");
const Socket = require("socket.io");
const app = express();
const server = require("http").Server(app);
const io = require("socket.io")(server);
const axios = require("axios");

const users = [];
const port = 3001;

app.get("/", (req, res) => {
  res.send("Node Js is Here ");
});

const addUser = (userName, roomId) => {
  users.push({
    userName: userName,
    roomId: roomId,
  });
};

const userLeave = (userName) => {
  users = users.filter((user) => user.userName != userName);
};

const getRoomUsers = (roomId) => {
  return users.filter((user) => user.roomId == roomId);
};

io.on("connection", (socket) => {
  console.log("Someone Connected");
  socket.on("join-room", (roomId, userName) => {
    console.log("User Joined room");
    console.log(roomId);
    console.log(userName);
    socket.join(roomId);
    addUser(userName, roomId);
    socket.to(roomId).emit("user-connected", userName);
    userLeave(userName);
    io.to(roomId).emit("all-users", getRoomUsers(roomId));

    //
    axios
      .get("https://localhost:3001")
      .then((response) => {
        console.log(response.data);
      })
      .catch((error) => {
        console.error(error);
      });

    socket.on("disconnect", () => {
      socket.leave(roomId);
      io.to(roomId).emit("all-users", getRoomUsers(roomId));
    });
  });
});

server.listen(port, () => {
  console.log(`Zoom Clone API listening on localhost:${port}`);
});
